<a href="https://colab.research.google.com/github/erikaguiracocha/Capstone-Project/blob/main/extrapointerikaguiracocha.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Exploratory Data Analysis of Immigration to Canada (1980-2013)**

**Introduction**

In this project, I explore a dataset provided by the Government of Canada that details immigration trends from various countries to Canada between 1980 and 2013. This project is part of my learning journey in the Data Analysis Full-Stack Intensive Bootcamp at MySkill.

The main focus is on applying data analysis techniques such as data cleaning, exploration, and visualization using Python libraries like Pandas and Matplotlib. Through this project, I aim to strengthen my skills in working with real-world datasets and extract meaningful insights that tell a compelling story.

By following a step-by-step approach, I replicate the work of a previous analysis while adding my own understanding, reflections, and personal challenges faced during the process.

**Project Objectives**

To load and explore a real-world dataset using Pandas.

To clean and prepare the data for analysis by removing unnecessary columns and handling missing values.

To calculate and analyze the total number of immigrants per country from 1980 to 2013.

To visualize trends in immigration from selected countries (e.g., Haiti, China, India) using line plots.

To identify the top 5 countries with the highest immigration to Canada and visualize their trends over time.

To demonstrate the application of data analysis skills learned during the bootcamp in a real dataset context.

In [3]:
import pandas as pd

# URL for the dataset
URL = 'https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DV0101EN-SkillsNetwork/Data%20Files/Canada.xlsx'

# Load the dataset
df_can = pd.read_excel(URL, sheet_name='Canada by Citizenship', skiprows=range(20), skipfooter=2)

# Show the first few records
df_can.head()

,Type,Coverage,OdName,AREA,AreaName,REG,RegName,DEV,DevName,1980,...,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013
0,Immigrants,Foreigners,Afghanistan,935,Asia,5501,Southern Asia,902,Developing regions,16,...,2978,3436,3009,2652,2111,1746,1758,2203,2635,2004
1,Immigrants,Foreigners,Albania,908,Europe,925,Southern Europe,901,Developed regions,1,...,1450,1223,856,702,560,716,561,539,620,603
2,Immigrants,Foreigners,Algeria,903,Africa,912,Northern Africa,902,Developing regions,80,...,3616,3626,4807,3623,4005,5393,4752,4325,3774,4331
3,Immigrants,Foreigners,American Samoa,909,Oceania,957,Polynesia,902,Developing regions,0,...,0,0,1,0,0,0,0,0,0,0
4,Immigrants,Foreigners,Andorra,908,Europe,925,Southern Europe,901,Developed regions,0,...,0,0,1,1,0,0,0,0,1,1

In [4]:
# Check the column names
df_can.columns

# Get information about the data (data types, null values, etc.)
df_can.info()

# Check the shape of the dataframe (rows, columns)
df_can.shape

# Check for missing values in each column
df_can.isnull().sum()

# Summary statistics of the numeric columns
df_can.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 195 entries, 0 to 194
Data columns (total 43 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Type      195 non-null    object
 1   Coverage  195 non-null    object
 2   OdName    195 non-null    object
 3   AREA      195 non-null    int64
 4   AreaName  195 non-null    object
 5   REG       195 non-null    int64
 6   RegName   195 non-null    object
 7   DEV       195 non-null    int64
 8   DevName   195 non-null    object
 9   1980      195 non-null    int64
 10  1981      195 non-null    int64
 11  1982      195 non-null    int64
 12  1983      195 non-null    int64
 13  1984      195 non-null    int64
 14  1985      195 non-null    int64
 15  1986      195 non-null    int64
 16  1987      195 non-null    int64
 17  1988      195 non-null    int64
 18  1989      195 non-null    int64
 19  1990      195 non-null    int64
 20  1991      195 non-null    int64
 21  1992      195 non-null    int64
 22  1993      195 non-null    int64
 23  1994      195 non-null    int64
 24  1995      195 non-null    int64
 25  1996      195 non-null    int64
 26  1997      195 non-null    int64
 27  1998      195 non-null    int64
 28  1999      195 non-null    int64
 29  2000      195 non-null    int64
 30  2001      195 non-null    int64
 31  2002      195 non-null    int64
 32  2003      195 non-null    int64
 33  2004      195 non-null    int64
 34  2005      195 non-null    int64
 35  2006      195 non-null    int64
 36  2007      195 non-null    int64
 37  2008      195 non-null    int64
 38  2009      195 non-null    int64
 39  2010      195 non-null    int64
 40  2011      195 non-null    int64
 41  2012      195 non-null    int64
 42  2013      195 non-null    int64
dtypes: int64(37), object(6)
memory usage: 65.6+ KB

,AREA,REG,DEV,1980,1981,1982,1983,1984,1985,1986,...,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013
count,195.000000,195.000000,195.000000,195.000000,195.000000,195.000000,195.000000,195.000000,195.000000,195.000000,...,195.000000,195.000000,195.000000,195.000000,195.000000,195.000000,195.000000,195.000000,195.000000,195.000000
mean,912.764103,1249.015385,901.753846,508.394872,566.989744,534.723077,387.435897,376.497436,358.861538,441.271795,...,1190.169231,1320.292308,1266.958974,1191.820513,1246.394872,1275.733333,1420.287179,1262.533333,1313.958974,1320.702564
std,13.082835,1185.526885,0.431878,1949.588546,2152.643752,1866.997511,1204.333597,1198.246371,1079.309600,1225.576630,...,3710.505369,4425.957828,3926.717747,3443.542409,3694.573544,3829.630424,4462.946328,4030.084313,4247.555161,4237.951988
min,903.000000,905.000000,901.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,903.000000,914.000000,902.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.500000,...,19.000000,28.500000,25.000000,31.000000,31.000000,36.000000,40.500000,37.500000,42.500000,45.000000
50%,908.000000,922.000000,902.000000,13.000000,10.000000,11.000000,12.000000,13.000000,17.000000,18.000000,...,191.000000,210.000000,218.000000,198.000000,205.000000,214.000000,211.000000,179.000000,233.000000,213.000000
75%,922.000000,925.500000,902.000000,251.500000,295.500000,275.000000,173.000000,181.000000,197.000000,254.000000,...,756.500000,832.000000,842.000000,899.000000,934.500000,888.000000,932.000000,772.000000,783.000000,796.000000
max,935.000000,5501.000000,902.000000,22045.000000,24796.000000,20620.000000,10015.000000,10170.000000,9564.000000,9470.000000,...,36619.000000,42584.000000,33848.000000,28742.000000,30037.000000,29622.000000,38617.000000,36765.000000,34315.000000,34129.000000

In [10]:
# Verify columns df_can
print(df_can.columns)

Index(['Continent',    'Region',   'DevName',        1980,        1981,
              1982,        1983,        1984,        1985,        1986,
              1987,        1988,        1989,        1990,        1991,
              1992,        1993,        1994,        1995,        1996,
              1997,        1998,        1999,        2000,        2001,
              2002,        2003,        2004,        2005,        2006,
              2007,        2008,        2009,        2010,        2011,
              2012,        2013],
      dtype='object')

In [17]:
#7
df_can.tail()

,Country,AreaName,RegName,DevName,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
190,Viet Nam,Asia,South-Eastern Asia,Developing regions,1191,1829,2162,3404,7583,5907,...,1816,1852,3153,2574,1784,2171,1942,1723,1731,2112
191,Western Sahara,Africa,Northern Africa,Developing regions,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
192,Yemen,Asia,Western Asia,Developing regions,1,2,1,6,0,18,...,124,161,140,122,133,128,211,160,174,217
193,Zambia,Africa,Eastern Africa,Developing regions,11,17,11,7,16,9,...,56,91,77,71,64,60,102,69,46,59
194,Zimbabwe,Africa,Eastern Africa,Developing regions,72,114,102,44,32,29,...,1450,615,454,663,611,508,494,434,437,407

In [18]:
#8
df_can.info()
#help(df_can.info)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 195 entries, 0 to 194
Data columns (total 38 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Country   195 non-null    object
 1   AreaName  195 non-null    object
 2   RegName   195 non-null    object
 3   DevName   195 non-null    object
 4   nan       195 non-null    int64
 5   nan       195 non-null    int64
 6   nan       195 non-null    int64
 7   nan       195 non-null    int64
 8   nan       195 non-null    int64
 9   nan       195 non-null    int64
 10  nan       195 non-null    int64
 11  nan       195 non-null    int64
 12  nan       195 non-null    int64
 13  nan       195 non-null    int64
 14  nan       195 non-null    int64
 15  nan       195 non-null    int64
 16  nan       195 non-null    int64
 17  nan       195 non-null    int64
 18  nan       195 non-null    int64
 19  nan       195 non-null    int64
 20  nan       195 non-null    int64
 21  nan       195 non-null    int64
 22  nan       195 non-null    int64
 23  nan       195 non-null    int64
 24  nan       195 non-null    int64
 25  nan       195 non-null    int64
 26  nan       195 non-null    int64
 27  nan       195 non-null    int64
 28  nan       195 non-null    int64
 29  nan       195 non-null    int64
 30  nan       195 non-null    int64
 31  nan       195 non-null    int64
 32  nan       195 non-null    int64
 33  nan       195 non-null    int64
 34  nan       195 non-null    int64
 35  nan       195 non-null    int64
 36  nan       195 non-null    int64
 37  nan       195 non-null    int64
dtypes: int64(34), object(4)
memory usage: 58.0+ KB

In [19]:
#9
df_can.columns

Index([ 'Country', 'AreaName',  'RegName',  'DevName',        nan,        nan,
              nan,        nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,        nan,
              nan,        nan],
      dtype='object')

In [20]:
#10
df_can.index
#help(df_can.index)

RangeIndex(start=0, stop=195, step=1)

In [21]:
#11
print(type(df_can.columns))
print(type(df_can.index))

<class 'pandas.core.indexes.base.Index'>
<class 'pandas.core.indexes.range.RangeIndex'>

In [22]:
#12
df_can.columns.tolist()

['Country',
 'AreaName',
 'RegName',
 'DevName',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan]

In [23]:
#14
print(type(df_can.columns.tolist()))
print(type(df_can.index.tolist()))

<class 'list'>
<class 'list'>

In [24]:
#15
# size of dataframe (rows, columns)
df_can.shape

(195, 38)

In [26]:
#17
rename_col = {'OdName':'Country', 'AreaName':'Continent', 'RegName':'Region'}
df_can.rename(columns= rename_col, inplace=True)
df_can.columns

Index([  'Country', 'Continent',    'Region',   'DevName',         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan],
      dtype='object')

In [27]:
#18
df_can.head()

,Country,Continent,Region,DevName,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,Afghanistan,Asia,Southern Asia,Developing regions,16,39,39,47,71,340,...,2978,3436,3009,2652,2111,1746,1758,2203,2635,2004
1,Albania,Europe,Southern Europe,Developed regions,1,0,0,0,0,0,...,1450,1223,856,702,560,716,561,539,620,603
2,Algeria,Africa,Northern Africa,Developing regions,80,67,71,69,63,44,...,3616,3626,4807,3623,4005,5393,4752,4325,3774,4331
3,American Samoa,Oceania,Polynesia,Developing regions,0,1,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
4,Andorra,Europe,Southern Europe,Developed regions,0,0,0,0,0,0,...,0,0,1,1,0,0,0,0,1,1

In [28]:
#19
df_can['Total'] = df_can.select_dtypes(include='number').sum(axis=1)
# df_sum = df_can[[1980,1981]]
# help(df_can.sum)
# df_sum["Total"] = df_sum.sum(axis=1)
df_can.head(5)

,Country,Continent,Region,DevName,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Total
0,Afghanistan,Asia,Southern Asia,Developing regions,16,39,39,47,71,340,...,3436,3009,2652,2111,1746,1758,2203,2635,2004,58639
1,Albania,Europe,Southern Europe,Developed regions,1,0,0,0,0,0,...,1223,856,702,560,716,561,539,620,603,15699
2,Algeria,Africa,Northern Africa,Developing regions,80,67,71,69,63,44,...,3626,4807,3623,4005,5393,4752,4325,3774,4331,69439
3,American Samoa,Oceania,Polynesia,Developing regions,0,1,0,0,0,0,...,0,1,0,0,0,0,0,0,0,6
4,Andorra,Europe,Southern Europe,Developed regions,0,0,0,0,0,0,...,0,1,1,0,0,0,0,1,1,15

In [34]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns